# Generated by Django 2.0.2 on 2021-05-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leavetype', models.CharField(max_length=500)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('reason', models.TextField()),
                ('halfday', models.CharField(max_length=10)),
            ],
        ),
    ]
