# Generated by Django 3.2.3 on 2021-05-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='dateend',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='leave',
            name='datestart',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='leave',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='leave',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='nam',
            field=models.CharField(max_length=30),
        ),
    ]
